/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./public/index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#051424",
        "on-primary-container": "#798098",
        "on-primary-fixed": "#131b2e",
        "on-secondary-fixed-variant": "#004e5a",
        "error-container": "#93000a",
        "tertiary-fixed": "#e0e0ff",
        "on-surface-variant": "#c6c6cd",
        background: "#051424",
        "tertiary-fixed-dim": "#bdc2ff",
        surface: "#051424",
        "secondary-fixed-dim": "#2fd9f4",
        "inverse-on-surface": "#233143",
        "inverse-primary": "#565e74",
        "outline-variant": "#45464d",
        "on-background": "#d4e4fa",
        "on-surface": "#d4e4fa",
        "on-tertiary": "#131e8c",
        "inverse-surface": "#d4e4fa",
        "surface-container": "#122131",
        "on-secondary-container": "#00515d",
        "on-secondary-fixed": "#001f25",
        "tertiary-container": "#00055c",
        "on-primary-fixed-variant": "#3f465c",
        "surface-bright": "#2c3a4c",
        "on-secondary": "#00363e",
        "surface-container-high": "#1c2b3c",
        primary: "#bec6e0",
        "on-primary": "#283044",
        tertiary: "#bdc2ff",
        "surface-variant": "#273647",
        "on-error-container": "#ffdad6",
        "primary-fixed-dim": "#bec6e0",
        "on-tertiary-fixed": "#000767",
        "surface-container-highest": "#273647",
        error: "#ffb4ab",
        secondary: "#5de6ff",
        "surface-tint": "#bec6e0",
        outline: "#909097",
        "primary-container": "#0f172a",
        "on-tertiary-container": "#6c77e1",
        "surface-container-low": "#0d1c2d",
        "secondary-fixed": "#a2eeff",
        "secondary-container": "#00cbe6",
        "surface-container-lowest": "#010f1f",
        "on-tertiary-fixed-variant": "#2f3aa3",
        "primary-fixed": "#dae2fd",
        "on-error": "#690005",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "16px",
        "stack-lg": "64px",
        "stack-sm": "8px",
        "stack-md": "24px",
        unit: "4px",
        gutter: "24px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "code-sm": ["JetBrains Mono", "monospace"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "display-lg": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "code-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "600" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "display-lg-mobile": ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
